name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

  push:
    branches: [ master, dev, preview ]
    paths:
    - "src/**"
    - ".github/workflows/**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Generate Build Number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Build
      run: msbuild Build.slnf /restore -m -property:Configuration=Release -property:BUILD_BUILDNUMBER=${{steps.buildnumber.outputs.build_number}}

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: dotnet publish
      if: ${{ github.ref == 'refs/heads/master' }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate